# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookingglass_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Source')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Sources',
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ManyToManyField(to='lookingglass_app.Source'),
        ),
    ]
