# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookingglass_app', '0002_auto_20160407_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='source',
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='URL of the image'),
        ),
    ]
